# Generated by Django 3.2.4 on 2021-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('year_of_release', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'manual'), (2, 'automatic'), (3, 'robot')])),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
